```{r}

if (!require(pacman)) {install.packages("pacman")
  library(pacman)}
pacman::p_load("shiny","readxl","summarytools","webr","ggplot2","curl","Hmisc",
               "sjmisc","car","lawstat","DiagrammeR","skimr",
               "tidyr","dplyr","broom","tidyverse")

#--------------------- <프로그램 A4.2-3> ----------------------#
# 1 ui ---- 
ui = fluidPage(
# 1.1. title ----
  titlePanel("붓꽃자료 산점도"),
# 1.2. sidebar ----
  sidebarLayout(
    sidebarPanel(helpText("붓꽃 종과 산점도를 그리 두 변수를 선택하세요."),
# 1.2.1. checkbox ----
      checkboxGroupInput("species",label = "종 선택", 
                         choices = list("setosa", "versicolor", "virginica"),
                         selected = c("setosa",  "versicolor", "virginica" )),
# 1.2.2. selectInput1 ----
      selectInput("x_name",label = "x축 변수",
           choices = list("Sepal.Length", "Sepal.Width", 
                         "Petal.Length", "Petal.Width"),
           selected = "Sepal.Length"),
# 1.2.3. selectInput2 ----
      selectInput("y_name",label = "y축 변수",
           choices = list("Sepal.Length", "Sepal.Width", 
                         "Petal.Length", "Petal.Width"),
           selected = "Sepal.Width"),
), #sidebarPenel
# 1.3. mainPanel(output) ----
    mainPanel(
# 1.3.1. plot(output) ----
plotOutput("out")
) #mainPanel
) #sidebarLayout
) #fluidPage


# 2.server ----
server=function(input, output){
	  
output$out=renderPlot({
  
# 2.1. 종 선택 안하면 빈 plot ----
if( is.null(input$species) ){return()}

# 2.2. 입력 종과 일치하는 행만 선택----
row=which(iris$Species %in% input$species)

# 2.3. 선택 행 중에서 입력한 변수에 대응하는 열을 선택 ----	    
x=iris[row, input$x_name]; y=iris[row, input$y_name]

# 2.4. 산점도 플롯----
col=rep(0,dim(iris)[1])
col[iris$Species == "setosa"]="deeppink"
col[iris$Species == "versicolor"]="blue3"
col[iris$Species == "virginica"]="green3"

# 2.5. 산점도 출력----
plot(x,y, col=col[row], cex=2, main="산점도" )
legend("topright",  box.col='gray', horiz=TRUE, 
			      	   inset=0.01, bg="transparent",
			           legend=input$species, 
			           text.col=unique(col[row]))
		  })
} 
#-------------------------------------------------------------#
#server ----
shinyApp(ui, server)
```


```{r}
df<-iris
str(df)
table(df$Species)

# Species: setosa
species="setosa"
row=subset(df,Species==species)
table(row$Species)

# x_name: Sepal.Length
# y_name: Petal.Width
x=row[,"Sepal.Length"]
y=row[,"Petal.Width"]
cbind(x,y)

col=rep(0,dim(df)[1])
col[df$Species == "setosa"]="deeppink"
col[df$Species == "versicolor"]="blue3"
col[df$Species == "virginica"]="green3"

#outer mar default c(0,0,0,0)
#inner mar default c(5, 4, 4, 2) + 0.1.

# c(아래,왼쪽,위,오른쪽)크기설정
par(mar=c(5,4,4,2), oma=c(0,0,0,0)) 


plot(x,y, col=col, main="산점도" , cex=2) # 
legend("topright", box.col='gray', horiz=TRUE, 
       inset=0.01, bg="transparent",
       legend=species, 
       text.col=unique(col))
```